# Generated by Django 3.2.8 on 2021-11-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211120_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/defult.jpg', upload_to='blog/'),
        ),
    ]
